# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
