# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171123_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
