# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171204_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(storage=system.storage.ImageStorage(), upload_to='images/gallery')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
