# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0002_auto_20171208_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_h',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_w',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orgimg',
            field=models.ImageField(default='images/head/default.jpg', storage=system.storage.ImageStorage(), upload_to='images/head'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='headimg',
            field=models.ImageField(blank=True, upload_to='images/head'),
        ),
    ]
