# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_auto_20171212_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_r',
            field=models.FloatField(default=1),
        ),
    ]
