# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(height_field='height', storage=system.storage.ImageStorage(), upload_to='images', width_field='width')),
                ('height', models.PositiveIntegerField(default=200)),
                ('width', models.PositiveIntegerField(default=300)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
