# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='img',
            field=models.ImageField(height_field='height', storage=system.storage.ImageStorage(), upload_to='images/article', width_field='width'),
        ),
    ]
